[package]
name = "xmp_toolkit"
version = "0.1.0"
authors = ["Eric Scouten <scouten@adobe.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"

[build-dependencies]
cc = "1.0"
fs_extra = "1.1"

[dev-dependencies]
tempfile = "3.1"
