[package]
name = "xmp-rs"
version = "0.1.0"
authors = ["Eric Scouten <scouten@adobe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
